name: Playwright Tests
on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    # Runs every day at 8 PM Eastern Time
    - cron: '0 0 * * *'  # This cron expression runs at 12 AM UTC (which is 8 PM Eastern Time)

jobs:
  test:
    runs-on: ubuntu-20.04  # Use Ubuntu 20.04 for Playwright support

    env:
      AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
      AZURE_DEVOPS_ORGANIZATION: ${{ secrets.AZURE_DEVOPS_ORGANIZATION }}
      AZURE_DEVOPS_PROJECT: ${{ secrets.AZURE_DEVOPS_PROJECT }}
      AZURE_DEVOPS_REPOSITORY: ${{ secrets.AZURE_DEVOPS_REPOSITORY }}
      AZURE_DEVOPS_DIRECTORY: ${{ secrets.AZURE_DEVOPS_DIRECTORY }}

    steps:
    - name: Checkout GitHub repository
      uses: actions/checkout@v3

    - name: Set up Git for sparse checkout
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git clone --no-checkout https://$AZURE_DEVOPS_PAT:x-oauth-basic@dev.azure.com/$AZURE_DEVOPS_ORGANIZATION/$AZURE_DEVOPS_PROJECT/_git/$AZURE_DEVOPS_REPOSITORY azure-devops-repo
        cd azure-devops-repo
        git config core.sparseCheckout true
        echo "$AZURE_DEVOPS_DIRECTORY/" >> .git/info/sparse-checkout
        git checkout jmob/playwrightTest  # Checks out the feature branch

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: |
        cd azure-devops-repo/$AZURE_DEVOPS_DIRECTORY
        echo "Current directory:"
        pwd  # Print the current directory
        echo "Directory contents:"
        npm install
        npx playwright install  # Installs Playwright and necessary browsers
        sudo npx playwright install-deps

    - name: Run Playwright tests
      run: |
        cd azure-devops-repo/$AZURE_DEVOPS_DIRECTORY
        echo "Current directory:"
        pwd  # Print the current directory
        echo "Directory contents:"
        npx playwright test

    - name: Save current directory path
      id: save-path
      run: |
        cd azure-devops-repo/$AZURE_DEVOPS_DIRECTORY/playwright-report
        echo "::set-output name=path::$(pwd)"
        ls   # List directory contents

    - name: Download html report artifact
      uses: actions/download-artifact@v4.1.8
      with:
        pattern: '**/index.html'

    # - name: Upload Playwright HTML report
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: playwright-html-report
    #     path: ${{ steps.save-path.outputs.path }}/playwright-report/index.html

    # - name: Upload Playwright trace on failure
    #   if: failure() # Only run this step if the previous step fails
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: playwright-trace
    #     path: ${{ steps.save-path.outputs.path }}/playwright-report/trace.zip

