name: Playwright Tests
on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    # Runs every day at 8 PM Eastern Time
    - cron: '0 0 * * *'  # This cron expression runs at 12 AM UTC (which is 8 PM Eastern Time)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repository
      uses: actions/checkout@v2

    - name: Set up Git for sparse checkout
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git clone --no-checkout https://$(AZURE_DEVOPS_PAT):x-oauth-basic@dev.azure.com/$(AZURE_DEVOPS_ORGANIZATION)/$(AZURE_DEVOPS_PROJECT)/_git/$(AZURE_DEVOPS_REPOSITORY) azure-devops-repo
        cd azure-devops-repo
        git config core.sparseCheckout true
        echo "$(AZURE_DEVOPS_DIRECTORY)/" >> .git/info/sparse-checkout
        git checkout jmob/playwrightTest  # Checks out the feature branch

      env:
        AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        AZURE_DEVOPS_ORGANIZATION: ${{ secrets.AZURE_DEVOPS_ORGANIZATION }}
        AZURE_DEVOPS_PROJECT: ${{ secrets.AZURE_DEVOPS_PROJECT }}
        AZURE_DEVOPS_REPOSITORY: ${{ secrets.AZURE_DEVOPS_REPOSITORY }}
        AZURE_DEVOPS_DIRECTORY: ${{ secrets.AZURE_DEVOPS_DIRECTORY }}
