name: Playwright Tests
on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    # Runs every day at 8 PM Eastern Time
    - cron: '0 0 * * *'  # This cron expression runs at 12 AM UTC (which is 8 PM Eastern Time)

jobs:
  test:
    runs-on: ubuntu-20.04  # Use Ubuntu 20.04 for Playwright support

    env:
      AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
      AZURE_DEVOPS_ORGANIZATION: ${{ secrets.AZURE_DEVOPS_ORGANIZATION }}
      AZURE_DEVOPS_PROJECT: ${{ secrets.AZURE_DEVOPS_PROJECT }}
      AZURE_DEVOPS_REPOSITORY: 'Washington'
      FEATURE_BRANCH: 'jmob/playwrightTest'

    steps:
      - name: Clone PartnerTrack Playwright Tests
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone --no-checkout https://$AZURE_DEVOPS_PAT:x-oauth-basic@dev.azure.com/fullsteamllc/Washington/_git/Washington
          cd Washington          
          git config core.sparseCheckout true
          echo "/Fullsteam.Payments.QA/Fullsteam.Payments.UITests.Playwright/PartnerTrack" >> .git/info/sparse-checkout
          git checkout jmob/playwrightTest  # Checks out the feature branch
          echo "Current directory:"
          pwd  # Print the current directory
          ls -R  # List all contents of the repository to verify
          mv Fullsteam.Payments.QA/Fullsteam.Payments.UITests.Playwright/PartnerTrack $GITHUB_WORKSPACE/PartnerTrack
          cd $GITHUB_WORKSPACE
          pwd  # Print the current directory
          ls -R  # List all contents of the repository to verify

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE/PartnerTrack
          npm install
          npx playwright install 
          sudo npx playwright install-deps

      - name: Run Playwright tests
        run: |
          cd $GITHUB_WORKSPACE/PartnerTrack
          npx playwright test          
          cd playwright-report
          ls

      - name: Upload Playwright HTML report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-html-report
          path: PartnerTrack/playwright-report/index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1  # Example action for deploying to GitHub Pages
        with:
          branch: gh-pages  # Branch where GitHub Pages are hosted
          folder: extracted-artifact  # Folder containing the extracted artifact contents


    # - name: Upload Playwright trace on failure
    #   if: failure() # Only run this step if the previous step fails
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: playwright-trace
    #     path: ${{ steps.save-path.outputs.path }}/playwright-report/trace.zip

